apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-mtuan
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: hello-app-mtuan
  template:
    metadata:
      labels:
        app: hello-app-mtuan
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:3.0
        name: hello-app-mtuan
        ports:
        - containerPort: 8080
